name: sfwedding
favicon: null
layout_spectrum: 0.14524869387969375
typography_spectrum: 0.32160639693029225
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5320280448067933
  lightness: 0.562114046420902
  saturation: 0.4614117245655507
  rhythmicContrast: 0.5112130411434919
purpose: []
