name: sfwedding
favicon: null
layout_spectrum: 1
typography_spectrum: 0.32160639693029225
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000008'
    - '#c6b5ad'
    - '#ffccad'
    - '#ffffff'
    - '#243757'
  brandStrength: 0.625
  lightness: 0.562114046420902
  saturation: 0.125
  rhythmicContrast: 0.5112130411434919
purpose: []
